### ISSUE TITLE
What's the benefits of using YARN as kuber's scheduler?

### ISSUE THREAD

**Issue by resouer** [hortonworks/kubernetes-yarn#4]
Sorry to say that but I found no benefits in kubernetes-yarn integration ... If we just make yarn as kuber's scheduler .... 

Or, in this case, yarn can run hadoop jobs in dockers created by kuber??

**Comment by sidharta-s** [comment]
@resouer YARN-1964 adds support for running docker containers natively in YARN - it is orthogonal to Kubernetes-YARN. Also YARN-1964 is completely unrelated to spark.

**Comment by resouer** [comment]
OK, I think I have got your basic idea. Thanks a lot!
